/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "high_to_low.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Empty, Empty, AUTO)


PB_BIND(SetPWM, SetPWM, AUTO)


PB_BIND(CpuHeartbeat, CpuHeartbeat, AUTO)


PB_BIND(HighToLow, HighToLow, AUTO)




