/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "low_to_high.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(McuHeartbeat, McuHeartbeat, AUTO)


PB_BIND(LowToHigh, LowToHigh, AUTO)




