active_modules:
  api:
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: connector_1
    module: API
  auth:
    config_module:
      connection_timeout: 10
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: PlugEvents
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: connector_1
      token_provider:
        - implementation_id: main
          module_id: token_provider
      token_validator:
        - implementation_id: main
          module_id: token_validator
    module: Auth
  energy_manager:
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
    module: EnergyManager
  connector_1:
    config_module:
      ac_hlc_enabled: false
      max_current: 16
      ac_nominal_voltage: 230
      ac_enforce_hlc: true
      ac_hlc_use_5percent: true
      charge_mode: AC
      connector_id: 1
      country_code: DE
      ev_receipt_required: false
      evse_id: DE*PNX*E12345*1
      has_ventilation: true
      payment_enable_contract: false
      payment_enable_eim: true
      rcd_enabled: true
      session_logging: true
      session_logging_path: /tmp/everest-logs
      session_logging_xml: false
      three_phases: true
    connections:
      bsp:
        - implementation_id: board_support
          module_id: connector_1_powerpath
      hlc:
        - implementation_id: charger
          module_id: iso15118_charger
      slac:
        - implementation_id: main
          module_id: slac
    module: EvseManager
  grid_connection_point:
    config_module:
      fuse_limit_A: 40
      phase_count: 3
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: connector_1
    module: EnergyNode
  iso15118_charger:
    config_module:
      device: eth2
    module: EvseV2G
#  iso15118_charger:
#    config_module:
#      device: eth2
#    connections: {}
#    module: PyJosev
  persistent_store:
    config_module:
      sqlite_db_file_path: everest_persistent_store.db
    connections: {}
    module: PersistentStore
  setup:
    config_module:
      initialized_by_default: true
      localization: true
      online_check_host: lfenergy.org
      setup_simulation: true
      setup_wifi: true
    connections:
      store:
        - implementation_id: main
          module_id: persistent_store
    module: Setup
  slac:
    config_implementation:
      main:
        device: eth2
        evse_id: PIONIX_SAYS_HELLO
        nid: pionix!
        number_of_sounds: 10
    connections: {}
    module: EvseSlac
  token_provider:
    config_implementation:
      main:
        timeout: 10
        token: DEADBEEF
    connections:
      evse:
        - implementation_id: evse
          module_id: connector_1
    module: JsDummyTokenProvider
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: JsDummyTokenValidator
  connector_1_powerpath:
    connections: {}
    module: TiAM625SDK
